### ISSUE TITLE
TRclust or TSclust

### ISSUE THREAD

**Issue by ponomarevsy** [vondrakt/nanopore-read-annotation#3]
Dear All,

I am having trouble finding the TRclust R package anywhere but there is a TSclust package available. I am using R v4.0.3. Please let me know if this is the R version that is not supported or there is a typo in the package name. If that package indeed exists, where can it be downloaded from? Thank you!

**Comment by kavonrtep** [comment]
it a typo - the scripts are using TSclust, sorry

Petr

**Comment by ponomarevsy** [comment]
Gotcha! Thanks, @kavonrtep.
